### ISSUE TITLE
How can i get pre-trained model?

### ISSUE THREAD

**Issue by springkim** [onlyygo/faster-rcnn-base-on-NCNN#1]
I want pretrained model that you wrote in Demo code.
Regards.

**Comment by David-Jin** [comment]
@onlyygo where is the "./model/detection_final.ncnnbin"   and "./model/proposal_final.ncnnbin" ?

I cannot find in the tree.

**Comment by onlyygo** [comment]
here is:
https://drive.google.com/open?id=0B9OXtJAN3-R8UDZIZVRzTU4yU1E

**Comment by songzeceng** [comment]
https://drive.google.com/open?id=0B9OXtJAN3-R8UDZIZVRzTU4yU1E访问不了...至少国内访问不了
